homework folder and html forms
JulianOviedo/SOLVD-FE-training pull request #2
Opened 2024-02-26 08:44 UTC by NFartenadze

2024-02-28 11:10 UTC, NFartenadze commented
I didn't see task file somehow :') I will delete this and do the task according to requirements

2024-02-28 16:29 UTC, JulianOviedo commented on homeworks/nika-fartenadze/01-html/index.html
> +      <!-- i am not sure if setting width/height attributes is considered css :(, it didn't take entire page without them )-->
its ok ! dont worry

2024-02-28 16:30 UTC, JulianOviedo commented on homeworks/nika-fartenadze/01-html/contact.html
> +    <title>Document</title>
add title

2024-02-28 16:30 UTC, JulianOviedo approved these changes
why ds_store files ? delete them please

2024-02-28 16:31 UTC, JulianOviedo commented
> I didn't see task file somehow :') I will delete this and do the task according to requirements

![image](https://github.com/JulianOviedo/SOLVD-FE-training/assets/97484290/ac93a4a7-f684-4e9f-a441-4b8cc1b4bdbf)

2024-02-28 16:32 UTC, JulianOviedo requested changes
delete ds_store unnecesary files

2024-02-29 06:25 UTC, NFartenadze commented
I also removed ds_store files, i just forgot to commit them separately

2024-03-01 15:03 UTC, JulianOviedo approved these changes

2024-03-01 15:30 UTC, merged