Finished first homework
JulianOviedo/SOLVD-FE-training pull request #9
Opened 2024-02-26 21:11 UTC by ChepeGR

Replicated [example](https://www.figma.com/file/rDDQzjMzAjQL5NYzCQDiXd/Simple-portfolio-(only-HTML)?type=design&node-id=0-1&mode=design&t=M5vFBqj2PSZd3dSn-0)

2024-02-28 15:39 UTC, JulianOviedo requested changes
Why you used `<footer/>` tag many times ? 

Footer usually its placed at the end of the pages with usefull links like social-media (our example). And also by 99% times the webpage have only one footer tag

Also, there should be just one index.html (main file - home in our case) and the other can be just contact.html. Image you have many files and you have to look for and specific one and you have index 1,2,3,4,5,6,7,8, etc haha

<img width="1634" alt="image" src="https://github.com/JulianOviedo/SOLVD-FE-training/assets/97484290/36796cc8-285e-4378-a5e1-d811f76f054d">
doesnt looks like the example i provided, please re-check

2024-02-28 19:30 UTC, ChepeGR commented
Thank you for the feedback. I made a new PR based on the comments that you made. Let me know if you have any new comments.

2024-02-28 21:59 UTC, JulianOviedo commented on homeworks/eduardo-griboldi/contact.html
> +        <a href="file:///Users/chepegarciariboldi/Desktop/repoFrontEnd/SOLVD-FE-training/homeworks/eduardo-griboldi/contact.html"> Contact</a>
could be a `<nav/>`

2024-02-28 22:02 UTC, JulianOviedo commented on homeworks/eduardo-griboldi/contact.html
> +            <input id="Last-Name" type="text" placeholder="Your last name..."/>
in general its better to use camelCase naming convention for values in attributtes
https://www.techtarget.com/whatis/definition/CamelCase#:~:text=CamelCase%20is%20a%20way%20to,programming%20and%20computer%20naming%20conventions.

2024-02-28 22:04 UTC, JulianOviedo commented on homeworks/eduardo-griboldi/contact.html
> +            <select name="country" id="country">
here is one of the reasons why we use a convention naming haha.
`Country` its not the same as `country`

2024-02-28 22:06 UTC, JulianOviedo requested changes
<img width="1650" alt="image" src="https://github.com/JulianOviedo/SOLVD-FE-training/assets/97484290/25d58742-2749-4c0c-9fc9-254994a835c5">

looks bad, again..

<img width="365" alt="image" src="https://github.com/JulianOviedo/SOLVD-FE-training/assets/97484290/744ff12a-e955-46c9-83f5-d46375365dd2">

Also, when you change smth you should request the re-review

2024-03-01 14:41 UTC, JulianOviedo requested changes
<img width="424" alt="image" src="https://github.com/JulianOviedo/SOLVD-FE-training/assets/97484290/94b0cd39-33f8-4ba1-b64c-d9d8c331ba81">
cant see the profile img.
also, fix navigation between pages.. if i click home or contact in the navbar nothing happens

2024-03-01 15:27 UTC, closed without merging